### ISSUE TITLE
Error messages during boot

### ISSUE THREAD

**Issue by manlycode** [sunnlamp/whether-music#10]
When I run:
```
yard install
yard start
```

I see the following backtrace:
```
❯ yarn start
yarn run v1.22.4
$ if-env NODE_ENV=production && npm run start:prod || npm run start:dev
npm WARN lifecycle The node binary used for scripts is /var/folders/mn/14s8qzrd1d10n62jsmrxn1600000gn/T/yarn--1592838726236-0.3895130855075364/node but npm is using /usr/local/Cellar/node/14.4.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> whether-music@1.0.0 start:dev /Users/manlycode/git/manlycode/whether-music
> concurrently "nodemon --ignore 'client/*'" "npm run client"

[1] npm WARN lifecycle The node binary used for scripts is /var/folders/mn/14s8qzrd1d10n62jsmrxn1600000gn/T/yarn--1592838726236-0.3895130855075364/node but npm is using /usr/local/Cellar/node/14.4.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
[1]
[1] > whether-music@1.0.0 client /Users/manlycode/git/manlycode/whether-music
[1] > cd client && npm run start
[1]
[0] [nodemon] 1.19.4
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching dir(s): *.*
[0] [nodemon] watching extensions: js,mjs,json
[0] [nodemon] starting `node server.js`
[1] npm WARN lifecycle The node binary used for scripts is /var/folders/mn/14s8qzrd1d10n62jsmrxn1600000gn/T/yarn--1592838726236-0.3895130855075364/node but npm is using /usr/local/Cellar/node/14.4.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
[1]
[1] > whether-music@0.1.0 start /Users/manlycode/git/manlycode/whether-music/client
[1] > react-scripts start
[1]
[0] Listening on PORT 3001
[0] Error: Request failed with status code 400
[0]     at createError (/Users/manlycode/git/manlycode/whether-music/node_modules/axios/lib/core/createError.js:16:15)
[0]     at settle (/Users/manlycode/git/manlycode/whether-music/node_modules/axios/lib/core/settle.js:17:12)
[0]     at IncomingMessage.handleStreamEnd (/Users/manlycode/git/manlycode/whether-music/node_modules/axios/lib/adapters/http.js:236:11)
[0]     at IncomingMessage.emit (events.js:327:22)
[0]     at endReadableNT (_stream_readable.js:1224:12)
[0]     at processTicksAndRejections (internal/process/task_queues.js:84:21) {
[0]   config: {
[0]     url: 'https://accounts.spotify.com/api/token',
[0]     method: 'post',
[0]     params: { grant_type: 'client_credentials' },
[0]     headers: {
[0]       Accept: 'application/json, text/plain, */*',
[0]       'Content-Type': 'application/x-www-form-urlencoded',
[0]       Authorization: 'Basic dW5kZWZpbmVkOnVuZGVmaW5lZA==',
[0]       'User-Agent': 'axios/0.19.2'
[0]     },
[0]     transformRequest: [ [Function: transformRequest] ],
[0]     transformResponse: [ [Function: transformResponse] ],
[0]     timeout: 0,
[0]     adapter: [Function: httpAdapter],
[0]     xsrfCookieName: 'XSRF-TOKEN',
[0]     xsrfHeaderName: 'X-XSRF-TOKEN',
[0]     maxContentLength: -1,
[0]     validateStatus: [Function: validateStatus],
[0]     data: undefined
[0]   },
[0]   request: <ref *1> ClientRequest {
[0]     _events: [Object: null prototype] {
[0]       socket: [Function (anonymous)],
[0]       abort: [Function (anonymous)],
[0]       aborted: [Function (anonymous)],
[0]       error: [Function (anonymous)],
[0]       timeout: [Function (anonymous)],
[0]       prefinish: [Function: requestOnPrefinish]
[0]     },
[0]     _eventsCount: 6,
[0]     _maxListeners: undefined,
[0]     outputData: [],
[0]     outputSize: 0,
[0]     writable: true,
[0]     destroyed: false,
[0]     _last: true,
[0]     chunkedEncoding: false,
[0]     shouldKeepAlive: false,
[0]     useChunkedEncodingByDefault: true,
[0]     sendDate: false,
[0]     _removedConnection: false,
[0]     _removedContLen: false,
[0]     _removedTE: false,
[0]     _contentLength: 0,
[0]     _hasBody: true,
[0]     _trailer: '',
[0]     finished: true,
[0]     _headerSent: true,
[0]     socket: TLSSocket {
[0]       _tlsOptions: [Object],
[0]       _secureEstablished: true,
[0]       _securePending: false,
[0]       _newSessionPending: false,
[0]       _controlReleased: true,
[0]       secureConnecting: false,
[0]       _SNICallback: null,
[0]       servername: 'accounts.spotify.com',
[0]       alpnProtocol: false,
[0]       authorized: true,
[0]       authorizationError: null,
[0]       encrypted: true,
[0]       _events: [Object: null prototype],
[0]       _eventsCount: 10,
[0]       connecting: false,
[0]       _hadError: false,
[0]       _parent: null,
[0]       _host: 'accounts.spotify.com',
[0]       _readableState: [ReadableState],
[0]       _maxListeners: undefined,
[0]       _writableState: [WritableState],
[0]       allowHalfOpen: false,
[0]       _sockname: null,
[0]       _pendingData: null,
[0]       _pendingEncoding: '',
[0]       server: undefined,
[0]       _server: null,
[0]       ssl: [TLSWrap],
[0]       _requestCert: true,
[0]       _rejectUnauthorized: true,
[0]       parser: null,
[0]       _httpMessage: [Circular *1],
[0]       [Symbol(res)]: [TLSWrap],
[0]       [Symbol(verified)]: true,
[0]       [Symbol(pendingSession)]: null,
[0]       [Symbol(async_id_symbol)]: 10,
[0]       [Symbol(kHandle)]: [TLSWrap],
[0]       [Symbol(kSetNoDelay)]: false,
[0]       [Symbol(lastWriteQueueSize)]: 0,
[0]       [Symbol(timeout)]: null,
[0]       [Symbol(kBuffer)]: null,
[0]       [Symbol(kBufferCb)]: null,
[0]       [Symbol(kBufferGen)]: null,
[0]       [Symbol(kCapture)]: false,
[0]       [Symbol(kBytesRead)]: 0,
[0]       [Symbol(kBytesWritten)]: 0,
[0]       [Symbol(connect-options)]: [Object]
[0]     },
[0]     _header: 'POST /api/token?grant_type=client_credentials HTTP/1.1\r\n' +
[0]       'Accept: application/json, text/plain, */*\r\n' +
[0]       'Content-Type: application/x-www-form-urlencoded\r\n' +
[0]       'Authorization: Basic dW5kZWZpbmVkOnVuZGVmaW5lZA==\r\n' +
[0]       'User-Agent: axios/0.19.2\r\n' +
[0]       'Host: accounts.spotify.com\r\n' +
[0]       'Connection: close\r\n' +
[0]       'Content-Length: 0\r\n' +
[0]       '\r\n',
[0]     _onPendingData: [Function: noopPendingOutput],
[0]     agent: Agent {
[0]       _events: [Object: null prototype],
[0]       _eventsCount: 2,
[0]       _maxListeners: undefined,
[0]       defaultPort: 443,
[0]       protocol: 'https:',
[0]       options: [Object],
[0]       requests: {},
[0]       sockets: [Object],
[0]       freeSockets: {},
[0]       keepAliveMsecs: 1000,
[0]       keepAlive: false,
[0]       maxSockets: Infinity,
[0]       maxFreeSockets: 256,
[0]       maxCachedSessions: 100,
[0]       _sessionCache: [Object],
[0]       [Symbol(kCapture)]: false
[0]     },
[0]     socketPath: undefined,
[0]     method: 'POST',
[0]     maxHeaderSize: undefined,
[0]     insecureHTTPParser: undefined,
[0]     path: '/api/token?grant_type=client_credentials',
[0]     _ended: true,
[0]     res: IncomingMessage {
[0]       _readableState: [ReadableState],
[0]       _events: [Object: null prototype],
[0]       _eventsCount: 3,
[0]       _maxListeners: undefined,
[0]       socket: [TLSSocket],
[0]       httpVersionMajor: 1,
[0]       httpVersionMinor: 1,
[0]       httpVersion: '1.1',
[0]       complete: true,
[0]       headers: [Object],
[0]       rawHeaders: [Array],
[0]       trailers: {},
[0]       rawTrailers: [],
[0]       aborted: false,
[0]       upgrade: false,
[0]       url: '',
[0]       method: null,
[0]       statusCode: 400,
[0]       statusMessage: 'Bad Request',
[0]       client: [TLSSocket],
[0]       _consuming: false,
[0]       _dumped: false,
[0]       req: [Circular *1],
[0]       responseUrl: 'https://accounts.spotify.com/api/token?grant_type=client_credentials',
[0]       redirects: [],
[0]       [Symbol(kCapture)]: false
[0]     },
[0]     aborted: false,
[0]     timeoutCb: null,
[0]     upgradeOrConnect: false,
[0]     parser: null,
[0]     maxHeadersCount: null,
[0]     reusedSocket: false,
[0]     _redirectable: Writable {
[0]       _writableState: [WritableState],
[0]       _events: [Object: null prototype],
[0]       _eventsCount: 2,
[0]       _maxListeners: undefined,
[0]       _options: [Object],
[0]       _redirectCount: 0,
[0]       _redirects: [],
[0]       _requestBodyLength: 0,
[0]       _requestBodyBuffers: [],
[0]       _onNativeResponse: [Function (anonymous)],
[0]       _currentRequest: [Circular *1],
[0]       _currentUrl: 'https://accounts.spotify.com/api/token?grant_type=client_credentials',
[0]       [Symbol(kCapture)]: false
[0]     },
[0]     [Symbol(kCapture)]: false,
[0]     [Symbol(kNeedDrain)]: false,
[0]     [Symbol(corked)]: 0,
[0]     [Symbol(kOutHeaders)]: [Object: null prototype] {
[0]       accept: [Array],
[0]       'content-type': [Array],
[0]       authorization: [Array],
[0]       'user-agent': [Array],
[0]       host: [Array]
[0]     }
[0]   },
[0]   response: {
[0]     status: 400,
[0]     statusText: 'Bad Request',
[0]     headers: {
[0]       date: 'Mon, 22 Jun 2020 15:12:07 GMT',
[0]       'content-type': 'application/json',
[0]       'set-cookie': [Array],
[0]       'content-length': '63',
[0]       server: 'envoy',
[0]       'strict-transport-security': 'max-age=31536000',
[0]       'x-content-type-options': 'nosniff',
[0]       via: 'HTTP/2 edgeproxy, 1.1 google',
[0]       'alt-svc': 'clear',
[0]       connection: 'close'
[0]     },
[0]     config: {
[0]       url: 'https://accounts.spotify.com/api/token',
[0]       method: 'post',
[0]       params: [Object],
[0]       headers: [Object],
[0]       transformRequest: [Array],
[0]       transformResponse: [Array],
[0]       timeout: 0,
[0]       adapter: [Function: httpAdapter],
[0]       xsrfCookieName: 'XSRF-TOKEN',
[0]       xsrfHeaderName: 'X-XSRF-TOKEN',
[0]       maxContentLength: -1,
[0]       validateStatus: [Function: validateStatus],
[0]       data: undefined
[0]     },
[0]     request: <ref *1> ClientRequest {
[0]       _events: [Object: null prototype],
[0]       _eventsCount: 6,
[0]       _maxListeners: undefined,
[0]       outputData: [],
[0]       outputSize: 0,
[0]       writable: true,
[0]       destroyed: false,
[0]       _last: true,
[0]       chunkedEncoding: false,
[0]       shouldKeepAlive: false,
[0]       useChunkedEncodingByDefault: true,
[0]       sendDate: false,
[0]       _removedConnection: false,
[0]       _removedContLen: false,
[0]       _removedTE: false,
[0]       _contentLength: 0,
[0]       _hasBody: true,
[0]       _trailer: '',
[0]       finished: true,
[0]       _headerSent: true,
[0]       socket: [TLSSocket],
[0]       _header: 'POST /api/token?grant_type=client_credentials HTTP/1.1\r\n' +
[0]         'Accept: application/json, text/plain, */*\r\n' +
[0]         'Content-Type: application/x-www-form-urlencoded\r\n' +
[0]         'Authorization: Basic dW5kZWZpbmVkOnVuZGVmaW5lZA==\r\n' +
[0]         'User-Agent: axios/0.19.2\r\n' +
[0]         'Host: accounts.spotify.com\r\n' +
        'Connection: close\r\n' +
[0]         'Content-Length: 0\r\n' +
[0]         '\r\n',
[0]       _onPendingData: [Function: noopPendingOutput],
[0]       agent: [Agent],
[0]       socketPath: undefined,
[0]       method: 'POST',
[0]       maxHeaderSize: undefined,
[0]       insecureHTTPParser: undefined,
[0]       path: '/api/token?grant_type=client_credentials',
[0]       _ended: true,
[0]       res: [IncomingMessage],
[0]       aborted: false,
[0]       timeoutCb: null,
[0]       upgradeOrConnect: false,
[0]       parser: null,
[0]       maxHeadersCount: null,
[0]       reusedSocket: false,
[0]       _redirectable: [Writable],
[0]       [Symbol(kCapture)]: false,
[0]       [Symbol(kNeedDrain)]: false,
[0]       [Symbol(corked)]: 0,
[0]       [Symbol(kOutHeaders)]: [Object: null prototype]
[0]     },
[0]     data: { error: 'invalid_client', error_description: 'Invalid client' }
[0]   },
[0]   isAxiosError: true,
[0]   toJSON: [Function (anonymous)]
[0] }
[0] TypeError: Cannot read property 'access_token' of undefined
[0]     at /Users/manlycode/git/manlycode/whether-music/server.js:29:20
[0]     at processTicksAndRejections (internal/process/task_queues.js:97:5)
[1] Starting the development server...
[1]
[1] Compiled successfully!
```

**Comment by manlycode** [comment]
https://github.com/sunnlamp/whether-music/commit/5e4af89f56522311ebea8c7aefde4f705051d8a6 Addresses this problem.
